# Generated by Django 4.1.3 on 2023-01-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0002_books_bookimage_alter_books_bookpress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="bookImage",
            field=models.ImageField(default="1.png", upload_to="."),
        ),
        migrations.AlterField(
            model_name="books",
            name="bookPrice",
            field=models.FloatField(default=0),
        ),
    ]
