# Generated by Django 4.1.3 on 2023-01-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_alter_books_bookimage_alter_books_bookprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="bookImage",
            field=models.ImageField(default="1.png", upload_to="book"),
        ),
    ]
